import '../constants/constants.dart';

const LOGIN = 'login/token';
const PROFILE = 'profile';
const FORGETPASSWORD='login/reset_password';
const CHECKCODE='login/verify_code';
const CHANGEPASSWORD='login/change_password';
const RESENTCODE='login/resend_code';
const LOGOUT='logout';
const STUDENTCOURSES='student/courses';
int Id=63;
String STUDENTCOURSESMATERIAL='student/courses/${Id}/materials/?type=lecture';
const GETTICKETSCATEGORIES='tickets/categories';
const CHANGEPROFILEINFO='change_profile';
const GETTICKETS='tickets';
const GETTICKET='tickets/23';
const CREATETICKET='tickets/create';
const SENDMESSAGE='tickets/23/send';
const GETCOURSEFORMEETINGS='student/meeting_register';
const GETAVAILABLEMEETINGS='student/meeting_register/';
const GETMEETINGS='professor/meetings';
const GETSTUDENTMEETINGS='student/meetings';